"""
core/email_reporter.py
Send daily/weekly attendance reports via Gmail SMTP.
"""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email                import encoders

from config.admin_settings import (
    EMAIL_ENABLED, EMAIL_SENDER, EMAIL_PASSWORD,
    EMAIL_RECEIVER, EMAIL_SMTP_HOST, EMAIL_SMTP_PORT,
    EMAIL_SUBJECT_PREFIX,
)
from config.settings import ATTENDANCE_CSV
from core.attendance_stats import calculate_attendance_percentage, get_daily_summary
from utils.time_utils import current_date, current_timestamp
from utils.helpers import log_info, log_error


def _build_html_report(from_date: str, to_date: str) -> str:
    """Build a styled HTML email body with attendance stats."""
    stats   = calculate_attendance_percentage(from_date, to_date)
    summary = get_daily_summary(current_date())

    rows = ""
    for s in stats:
        color = (
            "#6EE7B7" if s["status"] == "Good" else
            "#FCD34D" if s["status"] == "Average" else
            "#FCA5A5"
        )
        rows += f"""
        <tr>
          <td style="padding:8px 12px;">{s['user_id']}</td>
          <td style="padding:8px 12px;">{s['name']}</td>
          <td style="padding:8px 12px;">{s['present']} / {s['total']}</td>
          <td style="padding:8px 12px; color:{color}; font-weight:600;">
            {s['percentage']}%
          </td>
          <td style="padding:8px 12px; color:{color};">{s['status']}</td>
        </tr>"""

    html = f"""
    <html><body style="font-family:Segoe UI,sans-serif;background:#0F1117;color:#E2E8F0;padding:24px;">
      <h2 style="color:#38BDF8;">FaceAI Attendance Report</h2>
      <p style="color:#64748B;">Generated: {current_timestamp()}</p>
      <p style="color:#64748B;">Period: {from_date} to {to_date}</p>

      <h3 style="color:#94A3B8;margin-top:24px;">Today's Summary ({summary['date']})</h3>
      <table style="border-collapse:collapse;margin-bottom:24px;">
        <tr>
          <td style="padding:6px 16px;background:#1E293B;border-radius:4px;">
            Present: <strong style="color:#6EE7B7;">{summary['present']}</strong>
          </td>
          <td style="padding:6px 16px;background:#1E293B;margin-left:8px;">
            Absent: <strong style="color:#FCA5A5;">{summary['absent']}</strong>
          </td>
          <td style="padding:6px 16px;background:#1E293B;">
            Rate: <strong style="color:#38BDF8;">{summary['percentage']}%</strong>
          </td>
        </tr>
      </table>

      <h3 style="color:#94A3B8;">Attendance Percentage ({from_date} → {to_date})</h3>
      <table style="width:100%;border-collapse:collapse;background:#1A2235;border-radius:8px;">
        <thead>
          <tr style="background:#0F172A;color:#64748B;font-size:12px;">
            <th style="padding:10px 12px;text-align:left;">ID</th>
            <th style="padding:10px 12px;text-align:left;">Name</th>
            <th style="padding:10px 12px;text-align:left;">Present/Total</th>
            <th style="padding:10px 12px;text-align:left;">Percentage</th>
            <th style="padding:10px 12px;text-align:left;">Status</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>

      <p style="margin-top:24px;color:#334155;font-size:12px;">
        This report was auto-generated by FaceAI Attendance System.
      </p>
    </body></html>
    """
    return html


def send_report(
    from_date: str,
    to_date:   str,
    attach_csv: bool = True,
) -> dict:
    """
    Send an attendance report email.

    Returns { "success": bool, "message": str }
    """
    if not EMAIL_ENABLED:
        return {
            "success": False,
            "message": (
                "Email is disabled. Open config/admin_settings.py, "
                "set EMAIL_ENABLED = True and fill in your Gmail credentials."
            ),
        }

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"{EMAIL_SUBJECT_PREFIX} Attendance Report {from_date} to {to_date}"
        msg["From"]    = EMAIL_SENDER
        msg["To"]      = EMAIL_RECEIVER

        html_body = _build_html_report(from_date, to_date)
        msg.attach(MIMEText(html_body, "html"))

        # Attach CSV
        if attach_csv and os.path.exists(ATTENDANCE_CSV):
            with open(ATTENDANCE_CSV, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename=attendance_{from_date}_{to_date}.csv",
            )
            msg.attach(part)

        with smtplib.SMTP(EMAIL_SMTP_HOST, EMAIL_SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())

        log_info(f"Attendance report emailed to {EMAIL_RECEIVER}.")
        return {"success": True, "message": f"Report sent to {EMAIL_RECEIVER}."}

    except smtplib.SMTPAuthenticationError:
        msg = (
            "Gmail authentication failed. "
            "Use an App Password, not your Gmail login password. "
            "Enable 2FA → Google Account → Security → App Passwords."
        )
        log_error(msg)
        return {"success": False, "message": msg}

    except Exception as e:
        log_error(f"Email failed: {e}")
        return {"success": False, "message": str(e)}
